[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

baseURL = 'http://gohugo.io/'
languageCode = 'ja'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "会社概要"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "サービス"
    weight = 2
    url = "/"
  [[menu.header]]
    name = "採用情報"
    weight = 3
    url = "/"
  [[menu.header]]
    name = "ブログ"
    weight = 4
    url = "blog"
  [[menu.header]]
    name = "お問い合わせ"
    weight = 5
    url = "/"

[params]
author = "株式会社NOTE"
user = "hello"
hostname = "gohugo.io"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"