[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

baseURL = "https://toshi0622.github.io"
languageCode = "ja"
theme = "hugo-theme-nightfall"

baseURL = "http://localhost:8080/"
languageCode = "ja"
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "会社概要"
    weight = 1
    url = "/"
  [[menu.header]]
    name = "サービス"
    weight = 2
    url = "/"
  [[menu.header]]
    name = "採用情報"
    weight = 3
    url = "/"
  [[menu.header]]
    name = "ブログ"
    weight = 4
    url = "/"
  [[menu.header]]
    name = "お問い合わせ"
    weight = 5
    url = "/"

[params]
author = "株式会社NOTE"
user = "Tanaka"
hostname = "gohugo.io"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "Instagram"
url = "https://www.instagram.com/"
pre = "<a href='https://www.instagram.com/' target='_blank'>"
post = "</a>"

[[params.social]]
key = 1
name = "Twitter"
url = "https://twitter.com/?lang=ja"
pre = "<a href='https://twitter.com/?lang=ja' target='_blank'>"
post = "</a>"

[[params.social]]
key = 2
name = "Email"
url = "mailto:email@example.com"
pre = "<a href='mailto:email@example.com' target='_blank'>"
post = "</a>"