[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

baseURL = "https://toshi0622.github.io"
languageCode = "ja"
theme = "hugo-theme-nightfall"
publishDir = "docs"
canonifyurls = true

[menu]
  [[menu.header]]
    name = "ホーム"
    weight = 1
    url = "/"
  [[menu.header]]
    name = "会社情報"
    weight = 2
    url = "/company/"
  [[menu.header]]
    name = "サービス"
    weight = 3
    url = "/service/"
  [[menu.header]]
    name = "採用情報"
    weight = 4
    url = "/recruit/"
  [[menu.header]]
    name = "お知らせ"
    weight = 5
    url = "/news/"

[params]
author = "LINK to the future"
user = "株式会社LINK"
mainSections = ["index"]

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "Instagram"
url = "https://www.instagram.com/"

[[params.social]]
key = 1
name = "X(旧Twitter)"
url = "https://twitter.com/?lang=ja"

[[params.social]]
key = 2
name = "Email"
url = "mailto:email@example.com"