[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

baseURL = "https://toshi0622.github.io"
languageCode = "ja"
theme = "hugo-theme-nightfall"
publishDir = "docs"
canonifyurls = true

[permalinks]
    news = "/news/:year/:month/:day/:slug/"
    company = "/company/:year/:month/:day/:slug/"

[menu]
  [[menu.header]]
    name = "ホーム"
    weight = 1
    url = "/"
  [[menu.header]]
    name = "企業情報"
    weight = 2
    url = "/company/"
  [[menu.header]]
    name = "事業戦略"
    weight = 3
    url = "/strategy/"
  [[menu.header]]
    name = "お知らせ"
    weight = 4
    url = "/news/"

[params]
author = "Revolution through IT"
user = "株式会社NOTE"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "Instagram"
url = "https://www.instagram.com/"

[[params.social]]
key = 1
name = "Twitter"
url = "https://twitter.com/?lang=ja"

[[params.social]]
key = 2
name = "Email"
url = "mailto:email@example.com"