[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[blackfriday]
hrefTargetBlank = true

baseURL = "https://toshi0622.github.io"
languageCode = "ja"
theme = "hugo-theme-nightfall"
publishDir = "docs"
canonifyurls = true
readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[menu]
  [[menu.header]]
    name = "株式会社LINK"
    weight = 1
    url = "/"
  [[menu.header]]
    name = "お問い合わせ"
    weight = 2
    url = "/inquiry"

[params]
author = "IT周りのお悩みを1週間で改善!"
about_link = "/landingPageAboutServices/"
mainSections = ["index"]