name: Build and Deploy

on:
  push:
    branches:
      - main # トリガーとなるブランチを指定

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      # ビルドコマンドを走らせる。installを忘れないこと。
      - run: yarn install && yarn build

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            rsync -avz --delete public/ /var/www/html/
